CREATE TABLE carts (
    user_id BIGINT PRIMARY KEY CHECK (user_id > 0),
    active_checkout UUID
);
CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES carts(user_id),
    product_id BIGINT NOT NULL CHECK (product_id > 0),
    product_name VARCHAR(150) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    CONSTRAINT uk_cart_user_product UNIQUE (user_id, product_id)
);
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkout_id UUID NOT NULL UNIQUE,
    idempotency_key UUID NOT NULL,
    user_id BIGINT NOT NULL CHECK (user_id > 0),
    total_amount NUMERIC(12,2) NOT NULL CHECK (total_amount >= 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING','CONFIRMED','CANCELLED')),
    phase VARCHAR(20) NOT NULL CHECK (phase IN ('RESERVING','CONFIRMING','RELEASING','COMPLETED','FAILED')),
    failure_reason VARCHAR(250),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_orders_user_key UNIQUE (user_id, idempotency_key)
);
CREATE INDEX idx_orders_user_id ON orders(user_id, id DESC);
CREATE INDEX idx_orders_recovery ON orders(next_attempt_at, id)
    WHERE phase IN ('RESERVING','CONFIRMING','RELEASING');
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    product_id BIGINT NOT NULL CHECK (product_id > 0),
    product_name VARCHAR(150) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    CONSTRAINT uk_order_items_product UNIQUE (order_id, product_id)
);
