CREATE TABLE addresses
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street  VARCHAR(150) NOT NULL,
    city    VARCHAR(100) NOT NULL,
    state   VARCHAR(100),
    country VARCHAR(100) NOT NULL,
    zipcode VARCHAR(20)  NOT NULL
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    email      VARCHAR(254) NOT NULL,
    phone      VARCHAR(30),
    role       VARCHAR(20)  NOT NULL DEFAULT 'CUSTOMER',
    address_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_address UNIQUE (address_id),
    CONSTRAINT ck_users_role CHECK (role IN ('CUSTOMER', 'ADMIN')),
    CONSTRAINT fk_users_address
        FOREIGN KEY (address_id) REFERENCES addresses (id)
);
