CREATE TABLE products
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(150)   NOT NULL,
    description    VARCHAR(2000),
    price          NUMERIC(12, 2) NOT NULL,
    stock_quantity INTEGER        NOT NULL,
    category       VARCHAR(100)   NOT NULL,
    image_url      VARCHAR(2048),
    active         BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP(6)   NOT NULL,
    updated_at     TIMESTAMP(6)   NOT NULL,
    CONSTRAINT ck_products_price CHECK (price >= 0),
    CONSTRAINT ck_products_stock_quantity CHECK (stock_quantity >= 0)
);
